name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [staging, production]
        include:
          - environment: staging
            docker_tag: staging-latest
            deploy_to: "staging"
          - environment: production
            docker_tag: latest
            deploy_to: "production"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your-app:${{ matrix.docker_tag }}

      - name: Deploy to ${{ matrix.environment }}
        if: github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/develop' && matrix.environment == 'staging')
        run: |
          echo "Deploying to ${{ matrix.deploy_to }} environment"
          # Tady můžete přidat příkazy pro nasazení vaší aplikace, například:
          # ssh user@your-server "docker pull ${{ secrets.DOCKER_USERNAME }}/your-app:${{ matrix.docker_tag }} && docker-compose up -d"
